// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBGTFkREZy96qMhiwSoBFDMRCRJFQQ2Bzw',
    appId: '1:335833182526:web:25fcd935013f88e96a7c6f',
    messagingSenderId: '335833182526',
    projectId: 'grad-app-35af4',
    authDomain: 'grad-app-35af4.firebaseapp.com',
    storageBucket: 'grad-app-35af4.appspot.com',
    measurementId: 'G-WD0Z65MSPH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCxVygrm4Suu3tSacTvuMyk1Z_2GZlgt0U',
    appId: '1:335833182526:android:8f1dcd0de1a3e3556a7c6f',
    messagingSenderId: '335833182526',
    projectId: 'grad-app-35af4',
    storageBucket: 'grad-app-35af4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyABUwjHG00JtgfLVvirmAvg3hBph0uClHA',
    appId: '1:335833182526:ios:3cfeb343f066bf686a7c6f',
    messagingSenderId: '335833182526',
    projectId: 'grad-app-35af4',
    storageBucket: 'grad-app-35af4.appspot.com',
    iosClientId: '335833182526-vqrkg1fvofqvf9h7fvp5djukv0esmmbd.apps.googleusercontent.com',
    iosBundleId: 'com.example.finalDart',
  );
}
